Function  /Script/Engine.CheatManager:BugIt
StrProperty  /Script/Engine.CheatManager:BugIt.ScreenShotDescription
Function  /Script/Engine.CheatManager:BugItGo
FloatProperty  /Script/Engine.CheatManager:BugItGo.Roll
FloatProperty  /Script/Engine.CheatManager:BugItGo.Yaw
FloatProperty  /Script/Engine.CheatManager:BugItGo.Pitch
FloatProperty  /Script/Engine.CheatManager:BugItGo.Z
FloatProperty  /Script/Engine.CheatManager:BugItGo.Y
FloatProperty  /Script/Engine.CheatManager:BugItGo.X
Function  /Script/Engine.CheatManager:BugItStringCreator
